# Generated by Django 3.2.12 on 2022-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profId', models.CharField(default='000', max_length=3, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('modules', models.ManyToManyField(blank=True, related_name='professors', to='api.Module')),
            ],
        ),
    ]
