# Generated by Django 3.2.12 on 2022-03-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.module')),
                ('professor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.professor')),
            ],
        ),
    ]
