# Generated by Django 3.2.12 on 2022-03-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
